const cliente = {
    "Cedula": "999874",
    "Tipodocumento":"CC",
    "Nombre1":"Sebastian",
    "Nombre2":"Fernando",
    "Apellido1":"Pineda",
    "Apellido2":"Lopez",
    "Dv":"",
    "Celular":"3014565767",
    "Telefono":"",
    "Empresa":"dd",
    "Ocupacion":"",
    "EstadoCivil":"",
    "Correo":"sebastianprueba@gmail.com",
    "Direccion":"",
    "Observaciones":"",
    "Autoriza":1,
    "FechaNacimiento":"2000-01-01T00:00:00",
    "Afiliacion":"4",
    "EpsArs":"",
    "Ciudad":"11",
    "Localidad":"001",
    "Genero":"No especificado",
    "Rural":0,
    "ValorConsulta":0,
    "Tipopersona":"Natural",
    "Responsabilidadfiscal":"ZZ",
    "Tributos":"ZZ",
    "Codpostal":"",
    "Observacionfidelizacion":"",
    "Regimen":"49",
    "Pais":"CO",
    "Listaprecios":"1",
    "Ventasbloqueadas":false,
    "Maxcupo":0,
    "Diascupo":0,
    "Sedecreacion":"1",
    "Creadopor":"999",
    "RH":"o+"
  }

export default cliente;